### ISSUE TITLE
Investigate and fix high CPU / GPU consumption

### ISSUE THREAD

**Issue by SolcAndMe** [fiatdao/fiat-i-ui#31]

**Comment by 0xTARC** [comment]
@SolcAndMe were you seeing this locally or on the deployed instance?

in my profiler the #1 and #2 largest impacts are react devtools
#3 was antd

there are some small improvements we can make by general refactoring usestate and useeffect calls but i don't see any obvious performance hangouts (besides getting rid of antd dependency and using different slider, https://github.com/fiatdao/fiat-i-ui/issues/10)

**Comment by 0xTARC** [comment]
running investigation thread
https://discord.com/channels/931941263371042866/1042526185701265428
