### ISSUE TITLE
Handle `underlierToCollateralToken` errors

### ISSUE THREAD

**Issue by SolcAndMe** [fiatdao/fiat-i-ui#45]
- wrap `underlierToCollateralToken` in a try-catch
- extract the error message and rethrow the extracted error

**Comment by 0xTARC** [comment]
did this for
underlierToCollateralToken here: cc618a481221c5dd071f27800c73103af032f7fb
collateralTokenToUnderlier here: f2c0973c5d2bc131790e4ce2542185154f3b90d6
